/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package primerproyectoprogra1;

/**
 *
 * @author Eduardo
 */
public class MainWindowInterface extends javax.swing.JFrame {

    /**
     * Creates new form MainWindowInterface
     */
    public MainWindowInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        sumandoNumerosLabel = new javax.swing.JLabel();
        formandoPalabrasLabel = new javax.swing.JLabel();
        sumandoGoButton = new javax.swing.JButton();
        formandoGoButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        mainMenuBar = new javax.swing.JMenuBar();
        archivoMenu = new javax.swing.JMenu();
        irMenu = new javax.swing.JMenu();
        formandoPalabrasItem = new javax.swing.JMenuItem();
        sumandoNumerosItem = new javax.swing.JMenuItem();
        salirmenuIten = new javax.swing.JMenuItem();
        ayudaMenu = new javax.swing.JMenu();
        aboutItem = new javax.swing.JMenuItem();
        manualIten = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Proyecto 1");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleLabel.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        titleLabel.setText("Primer Proyecto Programación 1");
        getContentPane().add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 108, -1, 59));

        sumandoNumerosLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        sumandoNumerosLabel.setText("SumandoNumeros");
        getContentPane().add(sumandoNumerosLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 218, -1, -1));

        formandoPalabrasLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        formandoPalabrasLabel.setText("FormandoPalabras");
        getContentPane().add(formandoPalabrasLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 218, -1, -1));

        sumandoGoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/plus-number.png"))); // NOI18N
        sumandoGoButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        sumandoGoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumandoGoButtonActionPerformed(evt);
            }
        });
        getContentPane().add(sumandoGoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 253, -1, -1));

        formandoGoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/text.png"))); // NOI18N
        formandoGoButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        formandoGoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formandoGoButtonActionPerformed(evt);
            }
        });
        getContentPane().add(formandoGoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(412, 253, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/624878906.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 360));

        mainMenuBar.setBorderPainted(false);

        archivoMenu.setText("Archivo");

        irMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/go.png"))); // NOI18N
        irMenu.setText("Ir a:");

        formandoPalabrasItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/text.png"))); // NOI18N
        formandoPalabrasItem.setText("Formando Palabras");
        formandoPalabrasItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formandoPalabrasItemActionPerformed(evt);
            }
        });
        irMenu.add(formandoPalabrasItem);

        sumandoNumerosItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/plus-number.png"))); // NOI18N
        sumandoNumerosItem.setText("Sumando Numeros");
        sumandoNumerosItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumandoNumerosItemActionPerformed(evt);
            }
        });
        irMenu.add(sumandoNumerosItem);

        archivoMenu.add(irMenu);

        salirmenuIten.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/out.png"))); // NOI18N
        salirmenuIten.setText("Salir");
        salirmenuIten.setToolTipText("");
        salirmenuIten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirmenuItenActionPerformed(evt);
            }
        });
        archivoMenu.add(salirmenuIten);

        mainMenuBar.add(archivoMenu);

        ayudaMenu.setText("Ayuda");

        aboutItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/info.png"))); // NOI18N
        aboutItem.setText("Acerca de");
        ayudaMenu.add(aboutItem);

        manualIten.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/help.png"))); // NOI18N
        manualIten.setText("Manual");
        ayudaMenu.add(manualIten);

        mainMenuBar.add(ayudaMenu);

        setJMenuBar(mainMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formandoGoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formandoGoButtonActionPerformed
        FormandoPalabrasFrame fpf = new FormandoPalabrasFrame();
        fpf.setVisible(true);
    }//GEN-LAST:event_formandoGoButtonActionPerformed

    private void sumandoGoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumandoGoButtonActionPerformed
        SumandoNumerosFrame snf = new SumandoNumerosFrame();
        snf.setVisible(true);
    }//GEN-LAST:event_sumandoGoButtonActionPerformed

    private void formandoPalabrasItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formandoPalabrasItemActionPerformed
        FormandoPalabrasFrame fpf = new FormandoPalabrasFrame();
        fpf.setVisible(true);
    }//GEN-LAST:event_formandoPalabrasItemActionPerformed

    private void sumandoNumerosItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumandoNumerosItemActionPerformed
        SumandoNumerosFrame snf = new SumandoNumerosFrame();
        snf.setVisible(true);
    }//GEN-LAST:event_sumandoNumerosItemActionPerformed

    private void salirmenuItenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirmenuItenActionPerformed
       System.exit(0);
       
    }//GEN-LAST:event_salirmenuItenActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutItem;
    private javax.swing.JMenu archivoMenu;
    private javax.swing.JMenu ayudaMenu;
    private javax.swing.JButton formandoGoButton;
    private javax.swing.JMenuItem formandoPalabrasItem;
    private javax.swing.JLabel formandoPalabrasLabel;
    private javax.swing.JMenu irMenu;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar mainMenuBar;
    private javax.swing.JMenuItem manualIten;
    private javax.swing.JMenuItem salirmenuIten;
    private javax.swing.JButton sumandoGoButton;
    private javax.swing.JMenuItem sumandoNumerosItem;
    private javax.swing.JLabel sumandoNumerosLabel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
