/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package primerproyectoprogra1;

/**
 *
 * @author Eduardo
 */
public class SumandoNumerosFrame extends javax.swing.JFrame {

    /**
     * Creates new form SumandoNumerosFrame
     */
    public SumandoNumerosFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelNumber1 = new javax.swing.JLabel();
        labelNumber2 = new javax.swing.JLabel();
        labelPlus = new javax.swing.JLabel();
        labelFondo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sumando Números");
        setMinimumSize(new java.awt.Dimension(540, 360));
        setName("frameSumandoNumeros"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(null);

        labelNumber1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        labelNumber1.setText("numero");
        getContentPane().add(labelNumber1);
        labelNumber1.setBounds(50, 110, 120, 160);

        labelNumber2.setText("Numero");
        getContentPane().add(labelNumber2);
        labelNumber2.setBounds(290, 190, 80, 70);

        labelPlus.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        labelPlus.setText("+");
        getContentPane().add(labelPlus);
        labelPlus.setBounds(230, 180, 39, 58);

        labelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/624878906.jpg"))); // NOI18N
        getContentPane().add(labelFondo);
        labelFondo.setBounds(0, 0, 612, 408);

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(250, 70, 34, 14);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SumandoNumerosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SumandoNumerosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SumandoNumerosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SumandoNumerosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SumandoNumerosFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelFondo;
    private javax.swing.JLabel labelNumber1;
    private javax.swing.JLabel labelNumber2;
    private javax.swing.JLabel labelPlus;
    // End of variables declaration//GEN-END:variables
}
